name: Documentation Issue
description: Report an issue with documentation or request documentation improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated documentation
        - Unclear documentation
        - Example needed
        - API reference issue
        - Tutorial/guide needed
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue?
      placeholder: README.md, SECURITY.md, JSDoc for i18n.configure(), etc.
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say?
      placeholder: Quote the current documentation or describe what's missing

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: The documentation should explain...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example
      description: Provide an example if applicable
      placeholder: |
        ```javascript
        // Example code to demonstrate the feature
        ```
      render: javascript

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this documentation improvement?
      options:
        - Nice to have
        - Important
        - Critical (blocking adoption/use)

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a pull request to fix this
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context
      placeholder: Related issues, similar documentation in other projects, etc.
