// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";

let languagePattern = /^[a-z]{2,3}$/i;

let scriptPattern = /^[A-Z][a-z]{3}$/;

let regionPattern = /^[A-Z]{2}$|^[0-9]{3}$/;

function parse(tag) {
  let parts = tag.split("-");
  let len = parts.length;
  if (len === 0) {
    return;
  }
  let lang = parts[0];
  if (lang === undefined) {
    return;
  }
  if (!languagePattern.test(lang)) {
    return;
  }
  let rest = parts.slice(1, len);
  let script = Stdlib_Option.flatMap(rest[0], s => {
    if (scriptPattern.test(s)) {
      return s;
    }
  });
  let regionIdx = Stdlib_Option.isSome(script) ? 1 : 0;
  let region = Stdlib_Option.flatMap(rest[regionIdx], r => {
    if (regionPattern.test(r)) {
      return r;
    }
  });
  let variantIdx = regionIdx + (
    Stdlib_Option.isSome(region) ? 1 : 0
  ) | 0;
  let variants = rest.slice(variantIdx, rest.length);
  return {
    language: lang.toLowerCase(),
    script: script,
    region: region,
    variants: variants
  };
}

function toString(tag) {
  let parts = [tag.language];
  Stdlib_Option.forEach(tag.script, s => {
    parts.push(s);
  });
  Stdlib_Option.forEach(tag.region, r => {
    parts.push(r);
  });
  tag.variants.forEach(v => {
    parts.push(v);
  });
  return parts.join("-");
}

let LanguageTag = {
  languagePattern: languagePattern,
  scriptPattern: scriptPattern,
  regionPattern: regionPattern,
  parse: parse,
  toString: toString
};

function fromString(s) {
  return Stdlib_Option.map(parse(s), tag => ({
    tag: tag,
    raw: toString(tag)
  }));
}

function fromStringExn(s) {
  let locale = fromString(s);
  if (locale !== undefined) {
    return locale;
  } else {
    return Stdlib_Exn.raiseError(`Invalid locale: ` + s);
  }
}

function toString$1(locale) {
  return locale.raw;
}

function language(locale) {
  return locale.tag.language;
}

function region(locale) {
  return locale.tag.region;
}

function script(locale) {
  return locale.tag.script;
}

function eq(a, b) {
  return a.raw === b.raw;
}

function compare(a, b) {
  return Primitive_string.compare(a.raw, b.raw) | 0;
}

function parent(locale) {
  let match = locale.tag.region;
  let match$1 = locale.tag.script;
  if (match !== undefined || match$1 !== undefined) {
    return fromString(locale.tag.language);
  }
}

function fallbackChain(locale) {
  let _current = locale;
  let _acc = [];
  while (true) {
    let acc = _acc;
    let current = _current;
    let newAcc = acc.concat([current]);
    let p = parent(current);
    if (p === undefined) {
      return newAcc;
    }
    _acc = newAcc;
    _current = p;
    continue;
  };
}

let defaultLocale = fromStringExn("en");

let $$Set;

let $$Map;

export {
  LanguageTag,
  fromString,
  fromStringExn,
  toString$1 as toString,
  language,
  region,
  script,
  eq,
  compare,
  parent,
  fallbackChain,
  defaultLocale,
  $$Set,
  $$Map,
}
/* defaultLocale Not a pure module */
