// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Locale from "./Locale.res.mjs";
import * as Stdlib_Float from "@rescript/runtime/lib/es6/Stdlib_Float.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import Plural_engineWasm from "./plural_engine.wasm";

function categoryToString(cat) {
  switch (cat) {
    case "Zero" :
      return "zero";
    case "One" :
      return "one";
    case "Two" :
      return "two";
    case "Few" :
      return "few";
    case "Many" :
      return "many";
    case "Other" :
      return "other";
  }
}

function categoryFromString(s) {
  switch (s) {
    case "few" :
      return "Few";
    case "many" :
      return "Many";
    case "one" :
      return "One";
    case "other" :
      return "Other";
    case "two" :
      return "Two";
    case "zero" :
      return "Zero";
    default:
      return;
  }
}

function getOperands(n) {
  let absN = Math.abs(n);
  let str = absN.toString();
  let parts = str.split(".");
  let intPart = Stdlib_Option.getOr(parts[0], "0");
  let fracPart = Stdlib_Option.getOr(parts[1], "");
  let i = Stdlib_Option.getOr(Stdlib_Float.fromString(intPart), 0.0);
  let v = fracPart.length;
  let fracWithoutZeros = fracPart.replace(/0+$/, "");
  let w = fracWithoutZeros.length;
  let f = Stdlib_Option.getOr(Stdlib_Float.fromString(fracPart), 0.0);
  let t = Stdlib_Option.getOr(Stdlib_Float.fromString(fracWithoutZeros), 0.0);
  return {
    n: absN,
    i: i,
    v: v,
    w: w,
    f: f,
    t: t,
    c: 0,
    e: 0
  };
}

let wasmModule = Plural_engineWasm;

function isAvailable() {
  return Stdlib_Option.isSome(wasmModule);
}

function evaluateCategory(n, locale) {
  return Stdlib_Option.flatMap(wasmModule, wasm => categoryFromString(wasm.evaluate_plural(n, locale)));
}

let Wasm = {
  wasmModule: wasmModule,
  isAvailable: isAvailable,
  evaluateCategory: evaluateCategory
};

function en(op) {
  if (op.i === 1.0 && op.v === 0) {
    return "One";
  } else {
    return "Other";
  }
}

function fr(op) {
  if (op.i === 0.0 || op.i === 1.0) {
    return "One";
  } else {
    return "Other";
  }
}

function ru(op) {
  let mod10 = op.i % 10.0;
  let mod100 = op.i % 100.0;
  if (op.v === 0) {
    if (mod10 === 1.0 && mod100 !== 11.0) {
      return "One";
    } else if (mod10 >= 2.0 && mod10 <= 4.0 && (mod100 < 12.0 || mod100 > 14.0)) {
      return "Few";
    } else if (mod10 === 0.0 || mod10 >= 5.0 && mod10 <= 9.0 || mod100 >= 11.0 && mod100 <= 14.0) {
      return "Many";
    } else {
      return "Other";
    }
  } else {
    return "Other";
  }
}

function ar(op) {
  let mod100 = op.n % 100.0;
  if (op.n === 0.0) {
    return "Zero";
  } else if (op.n === 1.0) {
    return "One";
  } else if (op.n === 2.0) {
    return "Two";
  } else if (mod100 >= 3.0 && mod100 <= 10.0) {
    return "Few";
  } else if (mod100 >= 11.0 && mod100 <= 99.0) {
    return "Many";
  } else {
    return "Other";
  }
}

function pl(op) {
  let mod10 = op.i % 10.0;
  let mod100 = op.i % 100.0;
  if (op.v === 0) {
    if (op.i === 1.0) {
      return "One";
    } else if (mod10 >= 2.0 && mod10 <= 4.0 && (mod100 < 12.0 || mod100 > 14.0)) {
      return "Few";
    } else if (op.i !== 1.0 && (mod10 === 0.0 || mod10 === 1.0) || mod10 >= 5.0 && mod10 <= 9.0 || mod100 >= 12.0 && mod100 <= 14.0) {
      return "Many";
    } else {
      return "Other";
    }
  } else {
    return "Other";
  }
}

function ja(_op) {
  return "Other";
}

let Rules = {
  en: en,
  de: en,
  fr: fr,
  ru: ru,
  ar: ar,
  pl: pl,
  ja: ja,
  zh: ja,
  ko: ja
};

function getRuleForLocale(locale) {
  let lang = Stdlib_Option.getOr(locale.split("-")[0], locale).toLowerCase();
  switch (lang) {
    case "ar" :
      return ar;
    case "de" :
    case "en" :
      return en;
    case "fr" :
      return fr;
    case "pl" :
      return pl;
    case "ru" :
      return ru;
    case "ja" :
    case "ko" :
    case "zh" :
      return ja;
    default:
      return;
  }
}

function select(n, locale) {
  let cat = evaluateCategory(n, locale);
  if (cat !== undefined) {
    return cat;
  }
  let rule = getRuleForLocale(locale);
  if (rule !== undefined) {
    return rule(getOperands(n));
  } else {
    return "Other";
  }
}

function selectForLocale(n, locale) {
  return select(n, Locale.toString(locale));
}

export {
  categoryToString,
  categoryFromString,
  getOperands,
  Wasm,
  Rules,
  getRuleForLocale,
  select,
  selectForLocale,
}
/* wasmModule Not a pure module */
