// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Locale from "./Locale.res.mjs";
import * as Plural from "./Plural.res.mjs";

let units = [
  {
    timeUnit: "Year",
    seconds: 31536000.0,
    threshold: 0.5
  },
  {
    timeUnit: "Month",
    seconds: 2628000.0,
    threshold: 0.5
  },
  {
    timeUnit: "Week",
    seconds: 604800.0,
    threshold: 0.5
  },
  {
    timeUnit: "Day",
    seconds: 86400.0,
    threshold: 0.5
  },
  {
    timeUnit: "Hour",
    seconds: 3600.0,
    threshold: 0.5
  },
  {
    timeUnit: "Minute",
    seconds: 60.0,
    threshold: 0.5
  },
  {
    timeUnit: "Second",
    seconds: 1.0,
    threshold: 0.5
  }
];

function selectUnit(diffSeconds) {
  let absDiff = Math.abs(diffSeconds);
  let _index = 0;
  while (true) {
    let index = _index;
    if (index >= units.length) {
      return [
        "Second",
        diffSeconds
      ];
    }
    let info = units[index];
    if (info === undefined) {
      return [
        "Second",
        diffSeconds
      ];
    }
    let value = absDiff / info.seconds;
    if (value >= info.threshold) {
      return [
        info.timeUnit,
        diffSeconds / info.seconds
      ];
    }
    _index = index + 1 | 0;
    continue;
  };
}

function forLocale(locale, u) {
  let lang = Locale.language(locale);
  switch (lang) {
    case "ar" :
      switch (u) {
        case "Second" :
          return {
            singular: "ثانية",
            plural: "ثوانٍ",
            shortSingular: "ث",
            shortPlural: "ث",
            narrow: "ث"
          };
        case "Minute" :
          return {
            singular: "دقيقة",
            plural: "دقائق",
            shortSingular: "د",
            shortPlural: "د",
            narrow: "د"
          };
        case "Hour" :
          return {
            singular: "ساعة",
            plural: "ساعات",
            shortSingular: "س",
            shortPlural: "س",
            narrow: "س"
          };
        case "Day" :
          return {
            singular: "يوم",
            plural: "أيام",
            shortSingular: "ي",
            shortPlural: "ي",
            narrow: "ي"
          };
        case "Week" :
          return {
            singular: "أسبوع",
            plural: "أسابيع",
            shortSingular: "أس",
            shortPlural: "أس",
            narrow: "أس"
          };
        case "Month" :
          return {
            singular: "شهر",
            plural: "أشهر",
            shortSingular: "ش",
            shortPlural: "ش",
            narrow: "ش"
          };
        case "Year" :
          return {
            singular: "سنة",
            plural: "سنوات",
            shortSingular: "سن",
            shortPlural: "سن",
            narrow: "سن"
          };
      }
    case "de" :
      switch (u) {
        case "Second" :
          return {
            singular: "Sekunde",
            plural: "Sekunden",
            shortSingular: "Sek.",
            shortPlural: "Sek.",
            narrow: "s"
          };
        case "Minute" :
          return {
            singular: "Minute",
            plural: "Minuten",
            shortSingular: "Min.",
            shortPlural: "Min.",
            narrow: "m"
          };
        case "Hour" :
          return {
            singular: "Stunde",
            plural: "Stunden",
            shortSingular: "Std.",
            shortPlural: "Std.",
            narrow: "h"
          };
        case "Day" :
          return {
            singular: "Tag",
            plural: "Tage",
            shortSingular: "Tag",
            shortPlural: "Tage",
            narrow: "T"
          };
        case "Week" :
          return {
            singular: "Woche",
            plural: "Wochen",
            shortSingular: "Wo.",
            shortPlural: "Wo.",
            narrow: "W"
          };
        case "Month" :
          return {
            singular: "Monat",
            plural: "Monate",
            shortSingular: "Mon.",
            shortPlural: "Mon.",
            narrow: "M"
          };
        case "Year" :
          return {
            singular: "Jahr",
            plural: "Jahre",
            shortSingular: "J.",
            shortPlural: "J.",
            narrow: "J"
          };
      }
    case "es" :
      switch (u) {
        case "Second" :
          return {
            singular: "segundo",
            plural: "segundos",
            shortSingular: "s",
            shortPlural: "s",
            narrow: "s"
          };
        case "Minute" :
          return {
            singular: "minuto",
            plural: "minutos",
            shortSingular: "min",
            shortPlural: "min",
            narrow: "m"
          };
        case "Hour" :
          return {
            singular: "hora",
            plural: "horas",
            shortSingular: "h",
            shortPlural: "h",
            narrow: "h"
          };
        case "Day" :
          return {
            singular: "día",
            plural: "días",
            shortSingular: "d",
            shortPlural: "d",
            narrow: "d"
          };
        case "Week" :
          return {
            singular: "semana",
            plural: "semanas",
            shortSingular: "sem.",
            shortPlural: "sem.",
            narrow: "sem"
          };
        case "Month" :
          return {
            singular: "mes",
            plural: "meses",
            shortSingular: "m.",
            shortPlural: "m.",
            narrow: "m"
          };
        case "Year" :
          return {
            singular: "año",
            plural: "años",
            shortSingular: "a",
            shortPlural: "a",
            narrow: "a"
          };
      }
    case "fr" :
      switch (u) {
        case "Second" :
          return {
            singular: "seconde",
            plural: "secondes",
            shortSingular: "s",
            shortPlural: "s",
            narrow: "s"
          };
        case "Minute" :
          return {
            singular: "minute",
            plural: "minutes",
            shortSingular: "min",
            shortPlural: "min",
            narrow: "m"
          };
        case "Hour" :
          return {
            singular: "heure",
            plural: "heures",
            shortSingular: "h",
            shortPlural: "h",
            narrow: "h"
          };
        case "Day" :
          return {
            singular: "jour",
            plural: "jours",
            shortSingular: "j",
            shortPlural: "j",
            narrow: "j"
          };
        case "Week" :
          return {
            singular: "semaine",
            plural: "semaines",
            shortSingular: "sem.",
            shortPlural: "sem.",
            narrow: "sem"
          };
        case "Month" :
          return {
            singular: "mois",
            plural: "mois",
            shortSingular: "m.",
            shortPlural: "m.",
            narrow: "m"
          };
        case "Year" :
          return {
            singular: "an",
            plural: "ans",
            shortSingular: "a",
            shortPlural: "a",
            narrow: "a"
          };
      }
    case "ja" :
      switch (u) {
        case "Second" :
          return {
            singular: "秒",
            plural: "秒",
            shortSingular: "秒",
            shortPlural: "秒",
            narrow: "秒"
          };
        case "Minute" :
          return {
            singular: "分",
            plural: "分",
            shortSingular: "分",
            shortPlural: "分",
            narrow: "分"
          };
        case "Hour" :
          return {
            singular: "時間",
            plural: "時間",
            shortSingular: "時間",
            shortPlural: "時間",
            narrow: "時"
          };
        case "Day" :
          return {
            singular: "日",
            plural: "日",
            shortSingular: "日",
            shortPlural: "日",
            narrow: "日"
          };
        case "Week" :
          return {
            singular: "週間",
            plural: "週間",
            shortSingular: "週",
            shortPlural: "週",
            narrow: "週"
          };
        case "Month" :
          return {
            singular: "か月",
            plural: "か月",
            shortSingular: "か月",
            shortPlural: "か月",
            narrow: "月"
          };
        case "Year" :
          return {
            singular: "年",
            plural: "年",
            shortSingular: "年",
            shortPlural: "年",
            narrow: "年"
          };
      }
    case "ru" :
      switch (u) {
        case "Second" :
          return {
            singular: "секунда",
            plural: "секунд",
            shortSingular: "сек.",
            shortPlural: "сек.",
            narrow: "с"
          };
        case "Minute" :
          return {
            singular: "минута",
            plural: "минут",
            shortSingular: "мин.",
            shortPlural: "мин.",
            narrow: "м"
          };
        case "Hour" :
          return {
            singular: "час",
            plural: "часов",
            shortSingular: "ч.",
            shortPlural: "ч.",
            narrow: "ч"
          };
        case "Day" :
          return {
            singular: "день",
            plural: "дней",
            shortSingular: "дн.",
            shortPlural: "дн.",
            narrow: "д"
          };
        case "Week" :
          return {
            singular: "неделя",
            plural: "недель",
            shortSingular: "нед.",
            shortPlural: "нед.",
            narrow: "н"
          };
        case "Month" :
          return {
            singular: "месяц",
            plural: "месяцев",
            shortSingular: "мес.",
            shortPlural: "мес.",
            narrow: "м"
          };
        case "Year" :
          return {
            singular: "год",
            plural: "лет",
            shortSingular: "г.",
            shortPlural: "л.",
            narrow: "г"
          };
      }
    case "zh" :
      switch (u) {
        case "Second" :
          return {
            singular: "秒",
            plural: "秒",
            shortSingular: "秒",
            shortPlural: "秒",
            narrow: "秒"
          };
        case "Minute" :
          return {
            singular: "分钟",
            plural: "分钟",
            shortSingular: "分钟",
            shortPlural: "分钟",
            narrow: "分"
          };
        case "Hour" :
          return {
            singular: "小时",
            plural: "小时",
            shortSingular: "小时",
            shortPlural: "小时",
            narrow: "时"
          };
        case "Day" :
          return {
            singular: "天",
            plural: "天",
            shortSingular: "天",
            shortPlural: "天",
            narrow: "天"
          };
        case "Week" :
          return {
            singular: "周",
            plural: "周",
            shortSingular: "周",
            shortPlural: "周",
            narrow: "周"
          };
        case "Month" :
          return {
            singular: "个月",
            plural: "个月",
            shortSingular: "个月",
            shortPlural: "个月",
            narrow: "月"
          };
        case "Year" :
          return {
            singular: "年",
            plural: "年",
            shortSingular: "年",
            shortPlural: "年",
            narrow: "年"
          };
      }
    default:
      switch (u) {
        case "Second" :
          return {
            singular: "second",
            plural: "seconds",
            shortSingular: "sec",
            shortPlural: "sec",
            narrow: "s"
          };
        case "Minute" :
          return {
            singular: "minute",
            plural: "minutes",
            shortSingular: "min",
            shortPlural: "min",
            narrow: "m"
          };
        case "Hour" :
          return {
            singular: "hour",
            plural: "hours",
            shortSingular: "hr",
            shortPlural: "hr",
            narrow: "h"
          };
        case "Day" :
          return {
            singular: "day",
            plural: "days",
            shortSingular: "day",
            shortPlural: "days",
            narrow: "d"
          };
        case "Week" :
          return {
            singular: "week",
            plural: "weeks",
            shortSingular: "wk",
            shortPlural: "wks",
            narrow: "w"
          };
        case "Month" :
          return {
            singular: "month",
            plural: "months",
            shortSingular: "mo",
            shortPlural: "mos",
            narrow: "mo"
          };
        case "Year" :
          return {
            singular: "year",
            plural: "years",
            shortSingular: "yr",
            shortPlural: "yrs",
            narrow: "y"
          };
      }
  }
}

function forLocale$1(locale) {
  let lang = Locale.language(locale);
  switch (lang) {
    case "ar" :
      return {
        now: "الآن",
        yesterday: "أمس",
        tomorrow: "غداً",
        lastWeek: "الأسبوع الماضي",
        nextWeek: "الأسبوع القادم",
        lastMonth: "الشهر الماضي",
        nextMonth: "الشهر القادم",
        lastYear: "العام الماضي",
        nextYear: "العام القادم",
        ago: "منذ",
        inFuture: "خلال"
      };
    case "de" :
      return {
        now: "gerade eben",
        yesterday: "gestern",
        tomorrow: "morgen",
        lastWeek: "letzte Woche",
        nextWeek: "nächste Woche",
        lastMonth: "letzten Monat",
        nextMonth: "nächsten Monat",
        lastYear: "letztes Jahr",
        nextYear: "nächstes Jahr",
        ago: "vor",
        inFuture: "in"
      };
    case "es" :
      return {
        now: "ahora mismo",
        yesterday: "ayer",
        tomorrow: "mañana",
        lastWeek: "la semana pasada",
        nextWeek: "la próxima semana",
        lastMonth: "el mes pasado",
        nextMonth: "el próximo mes",
        lastYear: "el año pasado",
        nextYear: "el próximo año",
        ago: "hace",
        inFuture: "en"
      };
    case "fr" :
      return {
        now: "à l'instant",
        yesterday: "hier",
        tomorrow: "demain",
        lastWeek: "la semaine dernière",
        nextWeek: "la semaine prochaine",
        lastMonth: "le mois dernier",
        nextMonth: "le mois prochain",
        lastYear: "l'année dernière",
        nextYear: "l'année prochaine",
        ago: "il y a",
        inFuture: "dans"
      };
    case "ja" :
      return {
        now: "たった今",
        yesterday: "昨日",
        tomorrow: "明日",
        lastWeek: "先週",
        nextWeek: "来週",
        lastMonth: "先月",
        nextMonth: "来月",
        lastYear: "去年",
        nextYear: "来年",
        ago: "前",
        inFuture: "後"
      };
    case "ru" :
      return {
        now: "только что",
        yesterday: "вчера",
        tomorrow: "завтра",
        lastWeek: "на прошлой неделе",
        nextWeek: "на следующей неделе",
        lastMonth: "в прошлом месяце",
        nextMonth: "в следующем месяце",
        lastYear: "в прошлом году",
        nextYear: "в следующем году",
        ago: "назад",
        inFuture: "через"
      };
    case "zh" :
      return {
        now: "刚刚",
        yesterday: "昨天",
        tomorrow: "明天",
        lastWeek: "上周",
        nextWeek: "下周",
        lastMonth: "上个月",
        nextMonth: "下个月",
        lastYear: "去年",
        nextYear: "明年",
        ago: "前",
        inFuture: "后"
      };
    default:
      return {
        now: "just now",
        yesterday: "yesterday",
        tomorrow: "tomorrow",
        lastWeek: "last week",
        nextWeek: "next week",
        lastMonth: "last month",
        nextMonth: "next month",
        lastYear: "last year",
        nextYear: "next year",
        ago: "ago",
        inFuture: "in"
      };
  }
}

function getUnitName(locale, u, value, style) {
  let names = forLocale(locale, u);
  let category = Plural.selectForLocale(value, locale);
  switch (style) {
    case "Long" :
      if (category === "One") {
        return names.singular;
      } else {
        return names.plural;
      }
    case "Short" :
      if (category === "One") {
        return names.shortSingular;
      } else {
        return names.shortPlural;
      }
    case "Narrow" :
      return names.narrow;
  }
}

function formatRelative(config, value, u) {
  let absValue = Math.abs(value);
  let roundedValue = Math.round(absValue);
  let isPast = value < 0.0;
  let names = forLocale$1(config.locale);
  let lang = Locale.language(config.locale);
  let specialCase = config.numeric === "Auto" ? (
      absValue < 10.0 && u === "Second" ? names.now : (
          u === "Day" && roundedValue === 1.0 ? (
              isPast ? names.yesterday : names.tomorrow
            ) : (
              u === "Week" && roundedValue === 1.0 ? (
                  isPast ? names.lastWeek : names.nextWeek
                ) : (
                  u === "Month" && roundedValue === 1.0 ? (
                      isPast ? names.lastMonth : names.nextMonth
                    ) : (
                      u === "Year" && roundedValue === 1.0 ? (
                          isPast ? names.lastYear : names.nextYear
                        ) : undefined
                    )
                )
            )
        )
    ) : undefined;
  if (specialCase !== undefined) {
    return specialCase;
  }
  let unitName = getUnitName(config.locale, u, roundedValue, config.style);
  let valueStr = roundedValue.toString();
  let exit = 0;
  switch (lang) {
    case "ar" :
    case "de" :
      if (isPast) {
        return names.ago + ` ` + valueStr + ` ` + unitName;
      } else {
        return names.inFuture + ` ` + valueStr + ` ` + unitName;
      }
    case "es" :
    case "fr" :
      exit = 2;
      break;
    case "ja" :
    case "ko" :
    case "zh" :
      exit = 1;
      break;
    default:
      if (isPast) {
        return valueStr + ` ` + unitName + ` ` + names.ago;
      } else {
        return names.inFuture + ` ` + valueStr + ` ` + unitName;
      }
  }
  switch (exit) {
    case 1 :
      if (isPast) {
        return valueStr + unitName + names.ago;
      } else {
        return valueStr + unitName + names.inFuture;
      }
    case 2 :
      if (isPast) {
        return names.ago + ` ` + valueStr + ` ` + unitName;
      } else {
        return names.inFuture + ` ` + valueStr + ` ` + unitName;
      }
  }
}

function format(config, diffSeconds) {
  let match = selectUnit(diffSeconds);
  return formatRelative(config, match[1], match[0]);
}

let formatUnit = formatRelative;

function make(locale) {
  return {
    style: "Long",
    numeric: "Auto",
    locale: locale
  };
}

function withStyle(config, style) {
  return {
    style: style,
    numeric: config.numeric,
    locale: config.locale
  };
}

function withNumeric(config, numeric) {
  return {
    style: config.style,
    numeric: numeric,
    locale: config.locale
  };
}

function fromDates(config, from, to_) {
  let diffMs = to_.getTime() - from.getTime();
  let diffSeconds = diffMs / 1000.0;
  return format(config, diffSeconds);
}

function fromTimestamp(config, timestamp) {
  let now = Date.now();
  let diffSeconds = (timestamp - now) / 1000.0;
  return format(config, diffSeconds);
}

function fromISOString(config, isoString) {
  let date = new Date(isoString);
  if (Number.isNaN(date.getTime())) {
    return;
  } else {
    return fromTimestamp(config, date.getTime());
  }
}

export {
  make,
  withStyle,
  withNumeric,
  format,
  formatUnit,
  fromDates,
  fromTimestamp,
  fromISOString,
  selectUnit,
}
/* Locale Not a pure module */
