// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function make(locale) {
  return {
    locale: locale
  };
}

function fromString(s) {
  let base = Stdlib_Option.getOr(s.split("-")[0], s).toLowerCase();
  let locale;
  switch (base) {
    case "de" :
      locale = "German";
      break;
    case "es" :
      locale = "Spanish";
      break;
    case "fr" :
      locale = "French";
      break;
    case "it" :
      locale = "Italian";
      break;
    case "nl" :
      locale = "Dutch";
      break;
    case "pt" :
      locale = "Portuguese";
      break;
    case "ru" :
      locale = "Russian";
      break;
    default:
      locale = "English";
  }
  return {
    locale: locale
  };
}

let supportedLocales = [
  "en",
  "de",
  "fr",
  "es",
  "it",
  "pt",
  "nl",
  "ru"
];

function hasVowel(s) {
  let vowels = [
    "a",
    "e",
    "i",
    "o",
    "u"
  ];
  return s.split("").some(c => vowels.includes(c));
}

function stem(t, word) {
  let match = t.locale;
  switch (match) {
    case "English" :
      let s = {
        contents: word.toLowerCase()
      };
      if (s.contents.endsWith("sses") || s.contents.endsWith("ies")) {
        s.contents = s.contents.slice(0, s.contents.length - 2 | 0);
      } else if (s.contents.endsWith("s") && !s.contents.endsWith("ss") && s.contents.length > 3) {
        s.contents = s.contents.slice(0, s.contents.length - 1 | 0);
      }
      if (s.contents.endsWith("eed")) {
        if (s.contents.length > 4) {
          s.contents = s.contents.slice(0, s.contents.length - 1 | 0);
        }
      } else if (s.contents.endsWith("ed")) {
        let stem$1 = s.contents.slice(0, s.contents.length - 2 | 0);
        if (hasVowel(stem$1)) {
          s.contents = stem$1;
        }
      } else if (s.contents.endsWith("ing")) {
        let stem$2 = s.contents.slice(0, s.contents.length - 3 | 0);
        if (hasVowel(stem$2)) {
          s.contents = stem$2;
        }
      }
      let suffixes = [
        [
          "ational",
          "ate"
        ],
        [
          "tional",
          "tion"
        ],
        [
          "enci",
          "ence"
        ],
        [
          "anci",
          "ance"
        ],
        [
          "izer",
          "ize"
        ],
        [
          "ization",
          "ize"
        ],
        [
          "ation",
          "ate"
        ],
        [
          "ator",
          "ate"
        ],
        [
          "alism",
          "al"
        ],
        [
          "iveness",
          "ive"
        ],
        [
          "fulness",
          "ful"
        ],
        [
          "ousness",
          "ous"
        ],
        [
          "aliti",
          "al"
        ],
        [
          "iviti",
          "ive"
        ],
        [
          "biliti",
          "ble"
        ]
      ];
      suffixes.forEach(param => {
        let suffix = param[0];
        if (s.contents.endsWith(suffix) && s.contents.length > (suffix.length + 2 | 0)) {
          s.contents = s.contents.slice(0, s.contents.length - suffix.length | 0) + param[1];
          return;
        }
      });
      let step3 = [
        [
          "icate",
          "ic"
        ],
        [
          "ative",
          ""
        ],
        [
          "alize",
          "al"
        ],
        [
          "iciti",
          "ic"
        ],
        [
          "ical",
          "ic"
        ],
        [
          "ful",
          ""
        ],
        [
          "ness",
          ""
        ]
      ];
      step3.forEach(param => {
        let suffix = param[0];
        if (s.contents.endsWith(suffix) && s.contents.length > (suffix.length + 2 | 0)) {
          s.contents = s.contents.slice(0, s.contents.length - suffix.length | 0) + param[1];
          return;
        }
      });
      return s.contents;
    case "German" :
      let s$1 = {
        contents: word.toLowerCase()
      };
      let suffixes$1 = [
        "erin",
        "ern",
        "em",
        "en",
        "er",
        "es",
        "e",
        "s"
      ];
      suffixes$1.forEach(suffix => {
        if (s$1.contents.endsWith(suffix) && s$1.contents.length > (suffix.length + 2 | 0)) {
          s$1.contents = s$1.contents.slice(0, s$1.contents.length - suffix.length | 0);
          return;
        }
      });
      return s$1.contents;
    case "French" :
      let s$2 = {
        contents: word.toLowerCase()
      };
      let suffixes$2 = [
        "issements",
        "issement",
        "atrices",
        "atrice",
        "ateur",
        "ations",
        "ation",
        "ences",
        "ence",
        "ments",
        "ment",
        "ités",
        "ité",
        "ives",
        "ive",
        "eaux",
        "aux",
        "euses",
        "euse",
        "eux",
        "es",
        "é",
        "e"
      ];
      suffixes$2.forEach(suffix => {
        if (s$2.contents.endsWith(suffix) && s$2.contents.length > (suffix.length + 2 | 0)) {
          s$2.contents = s$2.contents.slice(0, s$2.contents.length - suffix.length | 0);
          return;
        }
      });
      return s$2.contents;
    case "Spanish" :
      let s$3 = {
        contents: word.toLowerCase()
      };
      let suffixes$3 = [
        "amientos",
        "imientos",
        "amiento",
        "imiento",
        "aciones",
        "ación",
        "adoras",
        "adores",
        "adora",
        "ador",
        "ancias",
        "ancia",
        "antes",
        "ante",
        "ables",
        "able",
        "ibles",
        "ible",
        "istas",
        "ista",
        "mente",
        "idad",
        "ivos",
        "iva",
        "ivo",
        "osas",
        "oso",
        "osa",
        "es",
        "os",
        "as",
        "a",
        "o"
      ];
      suffixes$3.forEach(suffix => {
        if (s$3.contents.endsWith(suffix) && s$3.contents.length > (suffix.length + 2 | 0)) {
          s$3.contents = s$3.contents.slice(0, s$3.contents.length - suffix.length | 0);
          return;
        }
      });
      return s$3.contents;
    case "Italian" :
      let s$4 = {
        contents: word.toLowerCase()
      };
      let suffixes$4 = [
        "amento",
        "amenti",
        "imento",
        "imenti",
        "azione",
        "azioni",
        "atore",
        "atori",
        "mente",
        "ità",
        "ivo",
        "iva",
        "ivi",
        "ive",
        "oso",
        "osa",
        "osi",
        "ose",
        "abile",
        "ibile",
        "ante",
        "ente",
        "i",
        "e",
        "a",
        "o"
      ];
      suffixes$4.forEach(suffix => {
        if (s$4.contents.endsWith(suffix) && s$4.contents.length > (suffix.length + 2 | 0)) {
          s$4.contents = s$4.contents.slice(0, s$4.contents.length - suffix.length | 0);
          return;
        }
      });
      return s$4.contents;
    case "Portuguese" :
      let s$5 = {
        contents: word.toLowerCase()
      };
      let suffixes$5 = [
        "amentos",
        "amento",
        "imentos",
        "imento",
        "ações",
        "ação",
        "adores",
        "ador",
        "mente",
        "idade",
        "ivo",
        "iva",
        "oso",
        "osa",
        "ável",
        "ível",
        "ante",
        "ente",
        "es",
        "os",
        "as",
        "a",
        "o"
      ];
      suffixes$5.forEach(suffix => {
        if (s$5.contents.endsWith(suffix) && s$5.contents.length > (suffix.length + 2 | 0)) {
          s$5.contents = s$5.contents.slice(0, s$5.contents.length - suffix.length | 0);
          return;
        }
      });
      return s$5.contents;
    case "Dutch" :
      let s$6 = {
        contents: word.toLowerCase()
      };
      let suffixes$6 = [
        "heden",
        "heid",
        "ingen",
        "ing",
        "elijk",
        "baar",
        "en",
        "e"
      ];
      suffixes$6.forEach(suffix => {
        if (s$6.contents.endsWith(suffix) && s$6.contents.length > (suffix.length + 2 | 0)) {
          s$6.contents = s$6.contents.slice(0, s$6.contents.length - suffix.length | 0);
          return;
        }
      });
      return s$6.contents;
    case "Russian" :
      let s$7 = {
        contents: word.toLowerCase()
      };
      let suffixes$7 = [
        "ость",
        "ости",
        "ние",
        "ния",
        "ами",
        "ями",
        "ов",
        "ев",
        "ей",
        "ах",
        "ях",
        "ом",
        "ем",
        "ий",
        "ый",
        "ая",
        "ое",
        "ие",
        "ые",
        "а",
        "я",
        "ы",
        "и",
        "у",
        "ю",
        "е",
        "о"
      ];
      suffixes$7.forEach(suffix => {
        if (s$7.contents.endsWith(suffix) && s$7.contents.length > (suffix.length + 2 | 0)) {
          s$7.contents = s$7.contents.slice(0, s$7.contents.length - suffix.length | 0);
          return;
        }
      });
      return s$7.contents;
  }
}

function stemWords(t, words) {
  return words.map(w => stem(t, w));
}

function stemText(t, text) {
  return text.split(" ").map(word => {
    if (/[a-zA-Zа-яА-Я]/.test(word)) {
      return stem(t, word);
    } else {
      return word;
    }
  }).join(" ");
}

export {
  make,
  fromString,
  stem,
  stemWords,
  stemText,
  supportedLocales,
}
/* No side effect */
